
// This file has been generated by the GUI designer. Do not modify.
namespace rmApplication
{
	public partial class OptionDialog
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Frame frameCommunication;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.ComboBox comboboxCommPort;
		
		private global::Gtk.Entry entryLocalIP;
		
		private global::Gtk.Entry entryLocalPort;
		
		private global::Gtk.Label labelCommPort;
		
		private global::Gtk.Label labelIP;
		
		private global::Gtk.Label labelPort;
		
		private global::Gtk.RadioButton radiobuttonNetwork;
		
		private global::Gtk.RadioButton radiobuttonSerial;
		
		private global::Gtk.Label GtkLabelCommunication;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.Table table7;
		
		private global::Gtk.ComboBox comboboxBaudRate;
		
		private global::Gtk.Entry entryPassword;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.RadioButton radiobuttonAddrWd2byte;
		
		private global::Gtk.RadioButton radiobuttonAddrWd4byte;
		
		private global::Gtk.Label GtkLabelCommon;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget rmApplication.OptionDialog
			this.Name = "rmApplication.OptionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child rmApplication.OptionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frameCommunication = new global::Gtk.Frame ();
			this.frameCommunication.Name = "frameCommunication";
			this.frameCommunication.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameCommunication.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.comboboxCommPort = global::Gtk.ComboBox.NewText ();
			this.comboboxCommPort.WidthRequest = 180;
			this.comboboxCommPort.Name = "comboboxCommPort";
			this.table2.Add (this.comboboxCommPort);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.comboboxCommPort]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryLocalIP = new global::Gtk.Entry ();
			this.entryLocalIP.CanFocus = true;
			this.entryLocalIP.Name = "entryLocalIP";
			this.entryLocalIP.IsEditable = true;
			this.entryLocalIP.InvisibleChar = '●';
			this.table2.Add (this.entryLocalIP);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryLocalIP]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryLocalPort = new global::Gtk.Entry ();
			this.entryLocalPort.CanFocus = true;
			this.entryLocalPort.Name = "entryLocalPort";
			this.entryLocalPort.IsEditable = true;
			this.entryLocalPort.InvisibleChar = '●';
			this.table2.Add (this.entryLocalPort);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryLocalPort]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelCommPort = new global::Gtk.Label ();
			this.labelCommPort.Name = "labelCommPort";
			this.labelCommPort.LabelProp = global::Mono.Unix.Catalog.GetString ("CommPort:");
			this.table2.Add (this.labelCommPort);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelCommPort]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelIP = new global::Gtk.Label ();
			this.labelIP.Name = "labelIP";
			this.labelIP.LabelProp = global::Mono.Unix.Catalog.GetString ("Local IP:");
			this.table2.Add (this.labelIP);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelIP]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelPort = new global::Gtk.Label ();
			this.labelPort.Name = "labelPort";
			this.labelPort.LabelProp = global::Mono.Unix.Catalog.GetString ("Local Port");
			this.table2.Add (this.labelPort);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelPort]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.radiobuttonNetwork = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Local Network"));
			this.radiobuttonNetwork.CanFocus = true;
			this.radiobuttonNetwork.Name = "radiobuttonNetwork";
			this.radiobuttonNetwork.Active = true;
			this.radiobuttonNetwork.DrawIndicator = true;
			this.radiobuttonNetwork.UseUnderline = true;
			this.radiobuttonNetwork.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table2.Add (this.radiobuttonNetwork);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.radiobuttonNetwork]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.radiobuttonSerial = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Serial Port"));
			this.radiobuttonSerial.CanFocus = true;
			this.radiobuttonSerial.Name = "radiobuttonSerial";
			this.radiobuttonSerial.DrawIndicator = true;
			this.radiobuttonSerial.UseUnderline = true;
			this.radiobuttonSerial.Group = this.radiobuttonNetwork.Group;
			this.table2.Add (this.radiobuttonSerial);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.radiobuttonSerial]));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table2);
			this.frameCommunication.Add (this.GtkAlignment2);
			this.GtkLabelCommunication = new global::Gtk.Label ();
			this.GtkLabelCommunication.Name = "GtkLabelCommunication";
			this.GtkLabelCommunication.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Communication</b>");
			this.GtkLabelCommunication.UseMarkup = true;
			this.frameCommunication.LabelWidget = this.GtkLabelCommunication;
			this.vbox6.Add (this.frameCommunication);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frameCommunication]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.table7 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.comboboxBaudRate = global::Gtk.ComboBox.NewText ();
			this.comboboxBaudRate.WidthRequest = 180;
			this.comboboxBaudRate.Name = "comboboxBaudRate";
			this.table7.Add (this.comboboxBaudRate);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table7 [this.comboboxBaudRate]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.entryPassword = new global::Gtk.Entry ();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.IsEditable = true;
			this.entryPassword.InvisibleChar = '●';
			this.table7.Add (this.entryPassword);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table7 [this.entryPassword]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Baud Rate:");
			this.table7.Add (this.label7);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table7 [this.label7]));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.table7.Add (this.label8);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table7 [this.label8]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox9.Add (this.table7);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.table7]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.radiobuttonAddrWd2byte = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Address Width:2byte"));
			this.radiobuttonAddrWd2byte.CanFocus = true;
			this.radiobuttonAddrWd2byte.Name = "radiobuttonAddrWd2byte";
			this.radiobuttonAddrWd2byte.Active = true;
			this.radiobuttonAddrWd2byte.DrawIndicator = true;
			this.radiobuttonAddrWd2byte.UseUnderline = true;
			this.radiobuttonAddrWd2byte.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox9.Add (this.radiobuttonAddrWd2byte);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.radiobuttonAddrWd2byte]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.radiobuttonAddrWd4byte = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Address Width:4byte"));
			this.radiobuttonAddrWd4byte.CanFocus = true;
			this.radiobuttonAddrWd4byte.Name = "radiobuttonAddrWd4byte";
			this.radiobuttonAddrWd4byte.DrawIndicator = true;
			this.radiobuttonAddrWd4byte.UseUnderline = true;
			this.radiobuttonAddrWd4byte.Group = this.radiobuttonAddrWd2byte.Group;
			this.vbox9.Add (this.radiobuttonAddrWd4byte);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.radiobuttonAddrWd4byte]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.GtkAlignment3.Add (this.vbox9);
			this.frame6.Add (this.GtkAlignment3);
			this.GtkLabelCommon = new global::Gtk.Label ();
			this.GtkLabelCommon.Name = "GtkLabelCommon";
			this.GtkLabelCommon.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Common Settings</b>");
			this.GtkLabelCommon.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabelCommon;
			this.vbox6.Add (this.frame6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame6]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			w1.Add (this.vbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox6]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Internal child rmApplication.OptionDialog.ActionArea
			global::Gtk.HButtonBox w24 = this.ActionArea;
			w24.Name = "dialog1_ActionArea";
			w24.Spacing = 10;
			w24.BorderWidth = ((uint)(5));
			w24.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonCancel]));
			w25.Expand = false;
			w25.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonOk]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 402;
			this.DefaultHeight = 336;
			this.Show ();
		}
	}
}
