
// This file has been generated by the GUI designer. Do not modify.
namespace rmApplication
{
	public partial class SubViewControl
	{
		private global::Gtk.VBox vboxMain;
		
		private global::Gtk.HBox hboxMenu;
		
		private global::Gtk.Label labelPage;
		
		private global::Gtk.ComboBox comboboxPage;
		
		private global::Gtk.Label labelTiming;
		
		private global::Gtk.Entry entryTiming;
		
		private global::Gtk.Button buttonDataLog;
		
		private global::Gtk.Button buttonDumpData;
		
		private global::Gtk.Label labelEmpty;
		
		private global::Gtk.Button buttonRsrc;
		
		private global::Gtk.Button buttonComm;
		
		private global::Gtk.HBox hboxDUTVer;
		
		private global::Gtk.Label labelDUTVer;
		
		private global::Gtk.Entry entryDUTVer;
		
		private global::Gtk.HBox hboxTgtVer;
		
		private global::Gtk.Label labelTgtVer;
		
		private global::Gtk.Entry entryTgtVer;
		
		private global::Gtk.Frame frameCommLog;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textviewCommLog;
		
		private global::Gtk.Label GtkLabelCommLog;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeviewMain;
		
		private global::Gtk.Entry entryTmpMessage;
		
		private global::Gtk.Statusbar statusbar;
		
		private global::Gtk.Label labelArea1;
		
		private global::Gtk.Label labelArea2;
		
		private global::Gtk.EventBox eventboxTx;
		
		private global::Gtk.Label labelTx;
		
		private global::Gtk.EventBox eventboxRx;
		
		private global::Gtk.Label labelRx;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget rmApplication.SubViewControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "rmApplication.SubViewControl";
			// Container child rmApplication.SubViewControl.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxMenu = new global::Gtk.HBox ();
			this.hboxMenu.Name = "hboxMenu";
			this.hboxMenu.Spacing = 6;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.labelPage = new global::Gtk.Label ();
			this.labelPage.WidthRequest = 50;
			this.labelPage.Name = "labelPage";
			this.labelPage.LabelProp = global::Mono.Unix.Catalog.GetString ("Page:");
			this.hboxMenu.Add (this.labelPage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.labelPage]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.comboboxPage = global::Gtk.ComboBox.NewText ();
			this.comboboxPage.WidthRequest = 180;
			this.comboboxPage.Name = "comboboxPage";
			this.hboxMenu.Add (this.comboboxPage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.comboboxPage]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.labelTiming = new global::Gtk.Label ();
			this.labelTiming.WidthRequest = 80;
			this.labelTiming.Name = "labelTiming";
			this.labelTiming.LabelProp = global::Mono.Unix.Catalog.GetString ("Timing(ms):");
			this.hboxMenu.Add (this.labelTiming);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.labelTiming]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.entryTiming = new global::Gtk.Entry ();
			this.entryTiming.WidthRequest = 80;
			this.entryTiming.CanFocus = true;
			this.entryTiming.Name = "entryTiming";
			this.entryTiming.Text = global::Mono.Unix.Catalog.GetString ("500");
			this.entryTiming.IsEditable = true;
			this.entryTiming.InvisibleChar = '●';
			this.hboxMenu.Add (this.entryTiming);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.entryTiming]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.buttonDataLog = new global::Gtk.Button ();
			this.buttonDataLog.WidthRequest = 80;
			this.buttonDataLog.CanFocus = true;
			this.buttonDataLog.Name = "buttonDataLog";
			this.buttonDataLog.UseUnderline = true;
			this.buttonDataLog.Label = global::Mono.Unix.Catalog.GetString ("Start Log");
			this.hboxMenu.Add (this.buttonDataLog);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.buttonDataLog]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.buttonDumpData = new global::Gtk.Button ();
			this.buttonDumpData.WidthRequest = 80;
			this.buttonDumpData.CanFocus = true;
			this.buttonDumpData.Name = "buttonDumpData";
			this.buttonDumpData.UseUnderline = true;
			this.buttonDumpData.Label = global::Mono.Unix.Catalog.GetString ("Dump");
			this.hboxMenu.Add (this.buttonDumpData);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.buttonDumpData]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.labelEmpty = new global::Gtk.Label ();
			this.labelEmpty.Name = "labelEmpty";
			this.hboxMenu.Add (this.labelEmpty);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.labelEmpty]));
			w7.Position = 6;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.buttonRsrc = new global::Gtk.Button ();
			this.buttonRsrc.WidthRequest = 90;
			this.buttonRsrc.CanFocus = true;
			this.buttonRsrc.Name = "buttonRsrc";
			this.buttonRsrc.UseUnderline = true;
			this.buttonRsrc.Label = global::Mono.Unix.Catalog.GetString ("Rsrc Open");
			this.hboxMenu.Add (this.buttonRsrc);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.buttonRsrc]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hboxMenu.Gtk.Box+BoxChild
			this.buttonComm = new global::Gtk.Button ();
			this.buttonComm.WidthRequest = 90;
			this.buttonComm.CanFocus = true;
			this.buttonComm.Name = "buttonComm";
			this.buttonComm.UseUnderline = true;
			this.buttonComm.Label = global::Mono.Unix.Catalog.GetString ("Comm Open");
			this.hboxMenu.Add (this.buttonComm);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxMenu [this.buttonComm]));
			w9.Position = 8;
			w9.Expand = false;
			w9.Fill = false;
			this.vboxMain.Add (this.hboxMenu);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxMenu]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxDUTVer = new global::Gtk.HBox ();
			this.hboxDUTVer.Name = "hboxDUTVer";
			this.hboxDUTVer.Spacing = 6;
			// Container child hboxDUTVer.Gtk.Box+BoxChild
			this.labelDUTVer = new global::Gtk.Label ();
			this.labelDUTVer.WidthRequest = 80;
			this.labelDUTVer.Name = "labelDUTVer";
			this.labelDUTVer.LabelProp = global::Mono.Unix.Catalog.GetString ("DUT Version");
			this.hboxDUTVer.Add (this.labelDUTVer);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxDUTVer [this.labelDUTVer]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hboxDUTVer.Gtk.Box+BoxChild
			this.entryDUTVer = new global::Gtk.Entry ();
			this.entryDUTVer.CanFocus = true;
			this.entryDUTVer.Name = "entryDUTVer";
			this.entryDUTVer.IsEditable = false;
			this.entryDUTVer.InvisibleChar = '●';
			this.hboxDUTVer.Add (this.entryDUTVer);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxDUTVer [this.entryDUTVer]));
			w12.Position = 1;
			this.vboxMain.Add (this.hboxDUTVer);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxDUTVer]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxTgtVer = new global::Gtk.HBox ();
			this.hboxTgtVer.Name = "hboxTgtVer";
			this.hboxTgtVer.Spacing = 6;
			// Container child hboxTgtVer.Gtk.Box+BoxChild
			this.labelTgtVer = new global::Gtk.Label ();
			this.labelTgtVer.WidthRequest = 80;
			this.labelTgtVer.Name = "labelTgtVer";
			this.labelTgtVer.LabelProp = global::Mono.Unix.Catalog.GetString ("Tgt Version");
			this.hboxTgtVer.Add (this.labelTgtVer);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxTgtVer [this.labelTgtVer]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hboxTgtVer.Gtk.Box+BoxChild
			this.entryTgtVer = new global::Gtk.Entry ();
			this.entryTgtVer.CanFocus = true;
			this.entryTgtVer.Name = "entryTgtVer";
			this.entryTgtVer.IsEditable = false;
			this.entryTgtVer.InvisibleChar = '●';
			this.hboxTgtVer.Add (this.entryTgtVer);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxTgtVer [this.entryTgtVer]));
			w15.Position = 1;
			this.vboxMain.Add (this.hboxTgtVer);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxTgtVer]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.frameCommLog = new global::Gtk.Frame ();
			this.frameCommLog.HeightRequest = 80;
			this.frameCommLog.Name = "frameCommLog";
			this.frameCommLog.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameCommLog.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewCommLog = new global::Gtk.TextView ();
			this.textviewCommLog.CanFocus = true;
			this.textviewCommLog.Name = "textviewCommLog";
			this.GtkScrolledWindow.Add (this.textviewCommLog);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frameCommLog.Add (this.GtkAlignment);
			this.GtkLabelCommLog = new global::Gtk.Label ();
			this.GtkLabelCommLog.Name = "GtkLabelCommLog";
			this.GtkLabelCommLog.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>CommLog</b>");
			this.GtkLabelCommLog.UseMarkup = true;
			this.frameCommLog.LabelWidget = this.GtkLabelCommLog;
			this.vboxMain.Add (this.frameCommLog);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.frameCommLog]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewMain = new global::Gtk.TreeView ();
			this.treeviewMain.CanFocus = true;
			this.treeviewMain.Name = "treeviewMain";
			this.GtkScrolledWindow1.Add (this.treeviewMain);
			this.vboxMain.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.GtkScrolledWindow1]));
			w22.Position = 4;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryTmpMessage = new global::Gtk.Entry ();
			this.entryTmpMessage.CanFocus = true;
			this.entryTmpMessage.Name = "entryTmpMessage";
			this.entryTmpMessage.IsEditable = true;
			this.entryTmpMessage.InvisibleChar = '●';
			this.vboxMain.Add (this.entryTmpMessage);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.entryTmpMessage]));
			w23.Position = 5;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.statusbar = new global::Gtk.Statusbar ();
			this.statusbar.Name = "statusbar";
			this.statusbar.Spacing = 6;
			// Container child statusbar.Gtk.Box+BoxChild
			this.labelArea1 = new global::Gtk.Label ();
			this.labelArea1.WidthRequest = 120;
			this.labelArea1.Name = "labelArea1";
			this.labelArea1.LabelProp = global::Mono.Unix.Catalog.GetString ("count cells");
			this.statusbar.Add (this.labelArea1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.labelArea1]));
			w24.Position = 1;
			// Container child statusbar.Gtk.Box+BoxChild
			this.labelArea2 = new global::Gtk.Label ();
			this.labelArea2.WidthRequest = 120;
			this.labelArea2.Name = "labelArea2";
			this.labelArea2.LabelProp = global::Mono.Unix.Catalog.GetString ("Send duration");
			this.statusbar.Add (this.labelArea2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.labelArea2]));
			w25.Position = 2;
			// Container child statusbar.Gtk.Box+BoxChild
			this.eventboxTx = new global::Gtk.EventBox ();
			this.eventboxTx.Name = "eventboxTx";
			// Container child eventboxTx.Gtk.Container+ContainerChild
			this.labelTx = new global::Gtk.Label ();
			this.labelTx.WidthRequest = 40;
			this.labelTx.Name = "labelTx";
			this.labelTx.LabelProp = global::Mono.Unix.Catalog.GetString ("Tx");
			this.eventboxTx.Add (this.labelTx);
			this.statusbar.Add (this.eventboxTx);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.eventboxTx]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child statusbar.Gtk.Box+BoxChild
			this.eventboxRx = new global::Gtk.EventBox ();
			this.eventboxRx.Name = "eventboxRx";
			// Container child eventboxRx.Gtk.Container+ContainerChild
			this.labelRx = new global::Gtk.Label ();
			this.labelRx.WidthRequest = 40;
			this.labelRx.Name = "labelRx";
			this.labelRx.LabelProp = global::Mono.Unix.Catalog.GetString ("Rx");
			this.eventboxRx.Add (this.labelRx);
			this.statusbar.Add (this.eventboxRx);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.eventboxRx]));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			this.vboxMain.Add (this.statusbar);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.statusbar]));
			w30.Position = 6;
			w30.Expand = false;
			w30.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
