
// This file has been generated by the GUI designer. Do not modify.
namespace rmApplication
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action ToolsAction;

		private global::Gtk.Action OpenAction;

		private global::Gtk.Action openViewFileAction;

		private global::Gtk.Action openMapFileAction;

		private global::Gtk.Action SaveAsAction;

		private global::Gtk.Action saveViewFileAction;

		private global::Gtk.Action saveMapFileAction;

		private global::Gtk.Action ExitAction;

		private global::Gtk.Action CustomizeAction;

		private global::Gtk.Action OptionsAction;

		private global::Gtk.Action SettingViewAction;

		private global::Gtk.Action SetupAction;

		private global::Gtk.Action HelpAction;

		private global::Gtk.Action AboutAction;

		private global::Gtk.VBox vboxMain;

		private global::Gtk.MenuBar menubar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget rmApplication.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.ToolsAction = new global::Gtk.Action("ToolsAction", global::Mono.Unix.Catalog.GetString("Tools"), null, null);
			this.ToolsAction.HideIfEmpty = false;
			this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tools");
			w1.Add(this.ToolsAction, null);
			this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("Open"), null, null);
			this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
			w1.Add(this.OpenAction, null);
			this.openViewFileAction = new global::Gtk.Action("openViewFileAction", global::Mono.Unix.Catalog.GetString("View File"), null, null);
			this.openViewFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View File");
			w1.Add(this.openViewFileAction, null);
			this.openMapFileAction = new global::Gtk.Action("openMapFileAction", global::Mono.Unix.Catalog.GetString("Map File"), null, null);
			this.openMapFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Map File");
			w1.Add(this.openMapFileAction, null);
			this.SaveAsAction = new global::Gtk.Action("SaveAsAction", global::Mono.Unix.Catalog.GetString("Save as"), null, null);
			this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as");
			w1.Add(this.SaveAsAction, null);
			this.saveViewFileAction = new global::Gtk.Action("saveViewFileAction", global::Mono.Unix.Catalog.GetString("View File"), null, null);
			this.saveViewFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View File");
			w1.Add(this.saveViewFileAction, null);
			this.saveMapFileAction = new global::Gtk.Action("saveMapFileAction", global::Mono.Unix.Catalog.GetString("Map File"), null, null);
			this.saveMapFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Map File");
			w1.Add(this.saveMapFileAction, null);
			this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
			w1.Add(this.ExitAction, null);
			this.CustomizeAction = new global::Gtk.Action("CustomizeAction", global::Mono.Unix.Catalog.GetString("Customize"), null, null);
			this.CustomizeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Customize");
			w1.Add(this.CustomizeAction, null);
			this.OptionsAction = new global::Gtk.Action("OptionsAction", global::Mono.Unix.Catalog.GetString("Options"), null, null);
			this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Options");
			w1.Add(this.OptionsAction, null);
			this.SettingViewAction = new global::Gtk.Action("SettingViewAction", global::Mono.Unix.Catalog.GetString("Setting View"), null, null);
			this.SettingViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Setting View");
			w1.Add(this.SettingViewAction, null);
			this.SetupAction = new global::Gtk.Action("SetupAction", global::Mono.Unix.Catalog.GetString("Setup"), null, null);
			this.SetupAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Setup");
			w1.Add(this.SetupAction, null);
			this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
			w1.Add(this.HelpAction, null);
			this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
			this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
			w1.Add(this.AboutAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "rmApplication.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child rmApplication.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar'><menu name='FileAction' action='FileAction'><menu name='OpenAction' action='OpenAction'><menuitem name='openViewFileAction' action='openViewFileAction'/><menuitem name='openMapFileAction' action='openMapFileAction'/></menu><menu name='SaveAsAction' action='SaveAsAction'><menuitem name='saveViewFileAction' action='saveViewFileAction'/><menuitem name='saveMapFileAction' action='saveMapFileAction'/></menu><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='SetupAction' action='SetupAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
			this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar")));
			this.menubar.Name = "menubar";
			this.vboxMain.Add(this.menubar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.menubar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 765;
			this.DefaultHeight = 383;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
